# Generated by Django 2.1 on 2018-08-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todolist_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
