# Generated by Django 2.1 on 2018-08-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20180815_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
